#!/bin/bash
arg=$1
echo ""
echo ""
echo "-------------------------Compiling--------------------"
echo ""
avr-gcc -Wall -g -Os -mmcu=atmega64a uC/wiesiek.c -o uC/wiesiek.o
avr-size -C uC/wiesiek.o
avr-objcopy -j .text -j .data -O ihex uC/wiesiek.o uC/wiesiek.hex
if [ $arg = "write" ]; then
    echo ""
    echo ""
    echo "-----------------------Flashing-----------------------"
    echo ""
    echo ""
    avrdude -c linuxgpio -p m64 -v -U flash:w:uC/wiesiek.hex:i
fi

